### ISSUE TITLE
Allow secure connections for S3 compatible storage

### ISSUE THREAD

**Issue by ossarga** [thelastpickle/cassandra-medusa#427]
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=13952031)

Currently secure connections to S3 compatible storage such as Minio are disallowed. The documentation states:

> Note: MinIO and other self hosted S3 compatible storage systems can only be used in unsecured (non SSL) mode with Medusa due to limitations in Apache Libcloud.

I believe this should be possible without any changes required to `libcloud`. We should be able to override the [global variables](https://github.com/apache/libcloud/blob/trunk/libcloud/security.py#L16) in the `libcloud.security` module to allow secure connections to S3 compatible storage.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1394) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1394
┆priority: Medium

**Comment by ossarga** [comment]
Solution for this is on branch https://github.com/thelastpickle/cassandra-medusa/tree/anthony/ISSUE-427/secure_s3_compatible_connection.

This patch requires just the unit tests before a pull request can be opened.

**Comment by smatvienko-tb** [comment]
Hey! I found that it is possible to add trust store certificates to the **certifi** for the remote S3 compatible storage and it works fine:

Here the hack:
```
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -ec
                - |
                  echo 'Adding trustcerts to the certifi storage...'
                  cat /etc/medusa/trustcerts.pem >> /opt/bitnami/python/lib/python3.9/site-packages/certifi/cacert.pem
                  echo 'Done'
```

Your PR is very useful. Looking forward to using it in the next release!
