### ISSUE TITLE
container couldn't be running with the uid/gid different than 999

### ISSUE THREAD

**Issue by ochekhi** [thelastpickle/cassandra-medusa#832]
Greetings,

I am facing an issue with starting a container using a different user than UID 999. Although the securityContext allows setting any userID, the container won't be created because docker-entrypoint.sh is located under /home/cassandra with restricted permissions only for the cassandra user (UID 999). Additionally, some environment variables are defined only for the cassandra user in the Dockerfile.

Should it be supported to run Medusa containers with any UID/GID?

```
medusa:
  securityContext:
    runAsGroup: 1000940000
    runAsNonRoot: true
    runAsUser: 1000940000
```

`Error: container create failed: time="2024-12-04T12:27:18+02:00" level=error msg="runc create failed: unable to start container process: exec: \"/home/cassandra/docker-entrypoint.sh\": stat /home/cassandra/docker-entrypoint.sh: permission denied"`
